services:
  backend:
    build: ./backend
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
  postgresql:
    image: postgres:14.15-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_caronas_ufrn